name: Build Epson Universal Power

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Flipper app
        uses: flipperdevices/flipperzero-ufbt-action@v0.1
        id: build
        with:
          sdk-url: https://up.momentum-fw.dev/builds/firmware/dev/flipper-z-f7-sdk-mntm-dev-d3f89dfe.zip
          sdk-hw-target: f7

      - name: Upload FAP
        uses: actions/upload-artifact@v4
        with:
          name: epson-universal-power
          path: ${{ steps.build.outputs.fap-artifacts }}
